version: '3.7'

services:
  gateway-service:
    container_name: gateway-service
    build: .
    networks:
      - net
    ports:
      - 8001:8001
    restart: unless-stopped

networks:
  net:
    driver: bridge
