apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: reckue/api-gateway:latest
        name: api-gateway
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: api-gateway
  type: ClusterIP
